import { StyleSheet } from 'react-native';
import { fontFamilies } from '../../../shared/theme';

const estilos = StyleSheet.create({
    conteudo: { paddingBottom: 40 },
    heroiFase: { height: 367, alignItems: 'center', paddingHorizontal: 16, paddingTop: 16 },
    formaProvisoria: { width: 260, height: 260, alignItems: 'center', justifyContent: 'center', borderRadius: 130, backgroundColor: 'rgba(200, 90, 68, 0.10)' },
    formaInterna: { width: 112, height: 112, borderRadius: 56, borderWidth: 2, borderColor: 'rgba(200, 90, 68, 0.32)' },
    formaProvisoriaCompacta: { width: 190, height: 190, borderRadius: 95 },
    formaInternaCompacta: { width: 82, height: 82, borderRadius: 41 },
    tituloFase: { color: '#222222', fontFamily: fontFamilies.bold, fontSize: 28, lineHeight: 35, textAlign: 'center', marginTop: 8 },
    diaCiclo: { color: '#5C5C59', fontFamily: fontFamilies.regular, fontSize: 16, lineHeight: 24, marginTop: 4 },
    acoes: { gap: 10, paddingHorizontal: 16 },
    botaoAcao: { height: 55, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, borderRadius: 12 },
    botaoPrimario: { backgroundColor: '#C85A44' },
    botaoSecundario: { backgroundColor: '#2C4C3B' },
    textoBotao: { color: '#FFFFFF', fontFamily: fontFamilies.bold, fontSize: 15, lineHeight: 24 },
    secaoPrevisao: { paddingHorizontal: 16, paddingTop: 32 },
    cartaoProximoCiclo: { minHeight: 135, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 20, borderRadius: 24, backgroundColor: '#FFFFFF', borderWidth: 0.7, borderColor: '#E6E2D8' },
    dataProximoCiclo: { flex: 1, paddingRight: 12 },
    rotuloPrevisao: { color: '#5C5C59', fontFamily: fontFamilies.medium, fontSize: 13, lineHeight: 20 },
    valorPrincipal: { color: '#222222', fontFamily: fontFamilies.bold, fontSize: 24, lineHeight: 36, textTransform: 'capitalize' },
    seloConfiabilidade: { width: 140, minHeight: 59, justifyContent: 'center', paddingHorizontal: 14, borderRadius: 16 },
    selo_baixa: { backgroundColor: '#F8DDD7' },
    selo_media: { backgroundColor: '#FBF3E0' },
    selo_alta: { backgroundColor: '#E2EFE8' },
    seloRotulo: { color: '#5C5C59', fontFamily: fontFamilies.medium, fontSize: 11, lineHeight: 16 },
    seloNivel: { color: '#222222', fontFamily: fontFamilies.bold, fontSize: 16, lineHeight: 24, textTransform: 'capitalize' },
    previsoesSecundarias: { flexDirection: 'row', gap: 12, marginTop: 12 },
    cartaoSecundario: { flex: 1, minHeight: 120, justifyContent: 'center', gap: 6, padding: 16, borderRadius: 24, backgroundColor: '#FFFFFF', borderWidth: 0.7, borderColor: '#E6E2D8' },
    valorSecundario: { color: '#222222', fontFamily: fontFamilies.bold, fontSize: 16, lineHeight: 23 },
    aviso: { color: '#5C5C59', fontFamily: fontFamilies.regular, fontSize: 13, lineHeight: 21, marginTop: 16 },
    incentivo: { color: '#5C5C59', fontFamily: fontFamilies.regular, fontSize: 13, lineHeight: 20, marginTop: 12 },
    alerta: { color: '#B43D3D', fontFamily: fontFamilies.bold, fontSize: 13, lineHeight: 20, marginTop: 12 },
    secaoTexto: { paddingHorizontal: 16, paddingTop: 40 },
    tituloSecao: { color: '#222222', fontFamily: fontFamilies.bold, fontSize: 18, lineHeight: 27, marginBottom: 16 },
    textoComMarcador: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
    marcador: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#C85A44', marginTop: 9 },
    descricaoFase: { flex: 1, color: '#5C5C59', fontFamily: fontFamilies.regular, fontSize: 16, lineHeight: 26 },
    secaoSintomas: { paddingHorizontal: 16, paddingTop: 40 },
    listaSintomas: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    sintoma: { width: '48.5%', minHeight: 43, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, borderRadius: 999, backgroundColor: '#FFFFFF', borderWidth: 0.7, borderColor: '#E6E2D8' },
    marcadorSintoma: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#C85A44' },
    textoSintoma: { flexShrink: 1, color: '#5C5C59', fontFamily: fontFamilies.medium, fontSize: 12, lineHeight: 18 },
    secaoDicas: { gap: 10, paddingHorizontal: 16, paddingTop: 40 },
    dica: { minHeight: 75, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, borderRadius: 16, backgroundColor: '#FBFAF6', borderWidth: 0.7, borderColor: '#E6E2D8' },
    numeroDica: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: '#F8DDD7' },
    textoNumeroDica: { color: '#C85A44', fontFamily: fontFamilies.bold, fontSize: 14 },
    textoDica: { flex: 1, color: '#5C5C59', fontFamily: fontFamilies.regular, fontSize: 14, lineHeight: 21 },
    estadoSemCiclo: { gap: 24, paddingHorizontal: 16, paddingTop: 24, paddingBottom: 40 },
    cartaoIntroducao: { minHeight: 666, alignItems: 'center', gap: 16, paddingHorizontal: 16, paddingVertical: 32, borderRadius: 24, backgroundColor: '#FFFFFF', borderWidth: 1.3, borderColor: 'rgba(200, 90, 68, 0.32)' },
    tituloSemCiclo: { color: '#222222', fontFamily: fontFamilies.bold, fontSize: 22, lineHeight: 30, textAlign: 'center' },
    descricaoSemCiclo: { color: '#5C5C59', fontFamily: fontFamilies.regular, fontSize: 15, lineHeight: 24, textAlign: 'center' },
    acoesSemCiclo: { alignSelf: 'stretch', gap: 10, marginTop: 8 },
    chamadaRecursos: { color: '#5C5C59', fontFamily: fontFamilies.bold, fontSize: 12, lineHeight: 18, letterSpacing: 1.68 },
    recursos: { gap: 10 },
    recurso: { minHeight: 92, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 0.7, borderColor: '#E6E2D8' },
    iconeRecurso: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#F8DDD7' },
    textoRecurso: { flex: 1 },
    tituloRecurso: { color: '#222222', fontFamily: fontFamilies.bold, fontSize: 14, lineHeight: 21 },
    descricaoRecurso: { color: '#5C5C59', fontFamily: fontFamilies.regular, fontSize: 13, lineHeight: 18 }
});

export { estilos };
