import { StyleSheet } from 'react-native';
import { fontFamilies } from '../../../shared/theme';

const estilosUso = StyleSheet.create({
    banner: { width: '100%', maxWidth: 350.01, height: 39.41, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', alignSelf: 'center', flexGrow: 0, flexShrink: 0, gap: 7, paddingVertical: 9, paddingHorizontal: 14, borderRadius: 10, backgroundColor: '#FBF3E0', borderWidth: 0.70489, borderColor: '#E8C97A' },
    textoBanner: { width: 142, height: 20, flexGrow: 0, flexShrink: 0, color: '#B07D2A', fontFamily: fontFamilies.semibold, fontWeight: '600', fontSize: 13, lineHeight: 20 },
    painel: { width: '100%', flexGrow: 0 },
    painelExpandido: { width: 'auto', alignSelf: 'stretch', marginHorizontal: -16 },
    cabecalhoPainel: { width: '100%', height: 28, alignItems: 'center', paddingTop: 10 },
    botaoPainel: { width: 124.99, height: 18, flexDirection: 'row', alignItems: 'center', flexGrow: 0, flexShrink: 0, gap: 4 },
    tituloPainel: { width: 93, height: 18, flexGrow: 0, flexShrink: 0, color: '#5C5C59', fontFamily: fontFamilies.medium, fontWeight: '500', fontSize: 12, lineHeight: 18, textAlign: 'center' },
    conteudoPainel: { width: '100%', alignItems: 'center', paddingTop: 8, paddingHorizontal: 16 },
    listaRegistros: { width: '100%', alignItems: 'flex-start', gap: 6 },
    registro: { width: '100%', height: 95, alignItems: 'flex-start', paddingVertical: 12, paddingHorizontal: 14, backgroundColor: '#F7F5F0', borderRadius: 10 },
    registroNaoConfirmado: { height: 91 },
    cabecalhoRegistro: { width: '100%', height: 23, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    dataRegistro: { height: 20, flexShrink: 0, color: '#222222', fontFamily: fontFamilies.bold, fontWeight: '700', fontSize: 13, lineHeight: 20 },
    linhaHorario: { width: '100%', height: 26, flexDirection: 'row', alignItems: 'center', gap: 6, paddingTop: 8 },
    linhaConfirmacao: { width: '100%', height: 22, flexDirection: 'row', alignItems: 'center', gap: 6, paddingTop: 4 },
    linhaSemConfirmacao: { width: '100%', height: 18, alignItems: 'flex-start' },
    rotuloHorarioProgramado: { width: 116, height: 18, flexShrink: 0, color: '#5C5C59', fontFamily: fontFamilies.regular, fontWeight: '400', fontSize: 12, lineHeight: 18 },
    rotuloConfirmacao: { width: 84, height: 18, flexShrink: 0, color: '#5C5C59', fontFamily: fontFamilies.regular, fontWeight: '400', fontSize: 12, lineHeight: 18 },
    horaRegistro: { height: 18, flexShrink: 0, color: '#222222', fontFamily: fontFamilies.semibold, fontWeight: '600', fontSize: 12, lineHeight: 18 },
    textoSemConfirmacao: { width: 133, height: 18, color: '#AAAAA5', fontFamily: fontFamilies.regular, fontWeight: '400', fontSize: 12, lineHeight: 18 },
    calendario: { width: '100%', maxWidth: 315.21, height: 256.43, alignItems: 'flex-start', flexGrow: 0, flexShrink: 0, padding: 8, backgroundColor: '#F7F5F0', borderRadius: 12 },
    calendarioSeisSemanas: { height: 291.43 },
    cabecalhoCalendario: { width: '100%', height: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    botaoMes: { width: 26, height: 22, flexDirection: 'row', alignItems: 'center', flexGrow: 0, flexShrink: 0, paddingVertical: 4, paddingHorizontal: 6 },
    setaProximo: { transform: [{ rotate: '180deg' }] },
    tituloMes: { height: 18, flexShrink: 0, color: '#222222', fontFamily: fontFamilies.bold, fontWeight: '700', fontSize: 12, lineHeight: 18 },
    margemDiasSemana: { width: '100%', height: 19.49, alignItems: 'flex-start', paddingTop: 6 },
    diasSemana: { width: '100%', height: 13.49, flexDirection: 'row' },
    diaSemana: { flex: 1, height: 13.49, color: '#AAAAA5', fontFamily: fontFamilies.semibold, fontWeight: '600', fontSize: 9, lineHeight: 14, letterSpacing: 0.18, textAlign: 'center' },
    margemGradeDias: { width: '100%', height: 175.96, alignItems: 'flex-start', paddingTop: 2 },
    margemGradeDiasSeisSemanas: { height: 210.96 },
    gradeDias: { width: '100%', height: 173.96, gap: 1 },
    gradeDiasSeisSemanas: { height: 208.96 },
    linhaSemana: { width: '100%', height: 34, flexDirection: 'row', gap: 1 },
    celulaDia: { flex: 1, height: 34, alignItems: 'center', justifyContent: 'center', gap: 2, borderRadius: 8 },
    celulaHoje: { borderWidth: 1, borderColor: '#E6E2D8' },
    numeroDia: { height: 12, color: '#222222', fontFamily: fontFamilies.regular, fontWeight: '400', fontSize: 12, lineHeight: 12, textAlign: 'center' },
    numeroDiaHoje: { fontFamily: fontFamilies.bold, fontWeight: '900' },
    diaComEstado: { color: '#FFFFFF' },
    celula_confirmado: { backgroundColor: 'rgba(44, 76, 59, 0.8)' },
    celula_foraDoPrazo: { backgroundColor: 'rgba(214, 140, 58, 0.8)' },
    celula_naoConfirmado: { backgroundColor: 'rgba(200, 90, 68, 0.8)' },
    legenda: { width: '100%', height: 23, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, paddingTop: 8, paddingHorizontal: 13 },
    itemLegenda: { height: 15, flexDirection: 'row', alignItems: 'center', flexGrow: 0, flexShrink: 0, gap: 4 },
    itemLegenda_confirmado: { width: 64.99 },
    itemLegenda_foraDoPrazo: { width: 74.99 },
    itemLegenda_naoConfirmado: { width: 84.99 },
    marcadorLegenda: { width: 5.99, height: 5.99, flexGrow: 0, flexShrink: 0, borderRadius: 2.99578 },
    marcador_confirmado: { backgroundColor: 'rgba(44, 76, 59, 0.8)' },
    marcador_foraDoPrazo: { backgroundColor: 'rgba(214, 140, 58, 0.8)' },
    marcador_naoConfirmado: { backgroundColor: 'rgba(200, 90, 68, 0.8)' },
    textoLegenda: { height: 15, flexGrow: 0, flexShrink: 0, color: '#5C5C59', fontFamily: fontFamilies.regular, fontWeight: '400', fontSize: 10, lineHeight: 15 },
    textoLegenda_confirmado: { width: 55 },
    textoLegenda_foraDoPrazo: { width: 65 },
    textoLegenda_naoConfirmado: { width: 75 }
});

export { estilosUso };
