//Centraliza os ícones usados pela interface sem carregar o catálogo inteiro do pacote.
import {ArrowLeftIcon} from 'phosphor-react-native/src/icons/ArrowLeft'
import {ArrowsClockwiseIcon} from 'phosphor-react-native/src/icons/ArrowsClockwise'
import {BellIcon} from 'phosphor-react-native/src/icons/Bell'
import {CalendarBlankIcon} from 'phosphor-react-native/src/icons/CalendarBlank'
import {CaretDownIcon} from 'phosphor-react-native/src/icons/CaretDown'
import {CaretLeftIcon} from 'phosphor-react-native/src/icons/CaretLeft'
import {CaretRightIcon} from 'phosphor-react-native/src/icons/CaretRight'
import {CheckIcon} from 'phosphor-react-native/src/icons/Check'
import {EnvelopeSimpleIcon} from 'phosphor-react-native/src/icons/EnvelopeSimple'
import {EyeIcon} from 'phosphor-react-native/src/icons/Eye'
import {EyeSlashIcon} from 'phosphor-react-native/src/icons/EyeSlash'
import {HouseIcon} from 'phosphor-react-native/src/icons/House'
import {InfoIcon} from 'phosphor-react-native/src/icons/Info'
import {LockKeyIcon} from 'phosphor-react-native/src/icons/LockKey'
import {MoonIcon} from 'phosphor-react-native/src/icons/Moon'
import {NotePencilIcon} from 'phosphor-react-native/src/icons/NotePencil'
import {PillIcon} from 'phosphor-react-native/src/icons/Pill'
import {ShieldCheckIcon} from 'phosphor-react-native/src/icons/ShieldCheck'
import {TrashIcon} from 'phosphor-react-native/src/icons/Trash'
import {UserIcon} from 'phosphor-react-native/src/icons/User'
import {WarningCircleIcon} from 'phosphor-react-native/src/icons/WarningCircle'
import {XIcon} from 'phosphor-react-native/src/icons/X'

export {ArrowLeftIcon, ArrowsClockwiseIcon, BellIcon, CalendarBlankIcon, CaretDownIcon, CaretLeftIcon, CaretRightIcon, CheckIcon, EnvelopeSimpleIcon, EyeIcon, EyeSlashIcon, HouseIcon, InfoIcon, LockKeyIcon, MoonIcon, NotePencilIcon, PillIcon, ShieldCheckIcon, TrashIcon, UserIcon, WarningCircleIcon, XIcon}
