//Centraliza os ícones usados pela interface sem carregar o catálogo inteiro do pacote.
import {ArrowLeftIcon} from 'phosphor-react-native/src/icons/ArrowLeft'
import {ArrowsClockwiseIcon} from 'phosphor-react-native/src/icons/ArrowsClockwise'
import {BellIcon} from 'phosphor-react-native/src/icons/Bell'
import {CaretDownIcon} from 'phosphor-react-native/src/icons/CaretDown'
import {CaretUpIcon} from 'phosphor-react-native/src/icons/CaretUp'
import {DropIcon} from 'phosphor-react-native/src/icons/Drop'
import {FirstAidKitIcon} from 'phosphor-react-native/src/icons/FirstAidKit'
import {HeartIcon} from 'phosphor-react-native/src/icons/Heart'
import {HouseIcon} from 'phosphor-react-native/src/icons/House'
import {InfoIcon} from 'phosphor-react-native/src/icons/Info'
import {LightningIcon} from 'phosphor-react-native/src/icons/Lightning'
import {LockKeyIcon} from 'phosphor-react-native/src/icons/LockKey'
import {MoonIcon} from 'phosphor-react-native/src/icons/Moon'
import {NotePencilIcon} from 'phosphor-react-native/src/icons/NotePencil'
import {PersonArmsSpreadIcon} from 'phosphor-react-native/src/icons/PersonArmsSpread'
import {ShieldCheckIcon} from 'phosphor-react-native/src/icons/ShieldCheck'
import {TrashIcon} from 'phosphor-react-native/src/icons/Trash'
import {UserIcon} from 'phosphor-react-native/src/icons/User'
import {UsersIcon} from 'phosphor-react-native/src/icons/Users'
import {WarningCircleIcon} from 'phosphor-react-native/src/icons/WarningCircle'
import {XIcon} from 'phosphor-react-native/src/icons/X'

export {ArrowLeftIcon, ArrowsClockwiseIcon, BellIcon, CaretDownIcon, CaretUpIcon, DropIcon, FirstAidKitIcon, HeartIcon, HouseIcon, InfoIcon, LightningIcon, LockKeyIcon, MoonIcon, NotePencilIcon, PersonArmsSpreadIcon, ShieldCheckIcon, TrashIcon, UserIcon, UsersIcon, WarningCircleIcon, XIcon}